// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

/** Returns true when running inside a Lovable editor iframe preview */
function isInLovablePreview(): boolean {
  if (typeof window === 'undefined') return false;
  const host = location.hostname;
  const PREVIEW_ZONES = ['lovableproject.com', 'lovableproject-dev.com', 'lovable.app', 'gpt-eng.com', 'gptengineer.run'];
  const onPreviewZone = PREVIEW_ZONES.some((z) => host === z || host.endsWith('.' + z));
  const framed = window.parent && window.parent !== window;
  return onPreviewZone && framed;
}

function createSupabaseClient() {
  const SUPABASE_URL =
    (typeof import.meta !== 'undefined' ? (import.meta.env as Record<string, string>)['VITE_SUPABASE_URL'] : undefined) ||
    (typeof process !== 'undefined' ? process.env['SUPABASE_URL'] : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== 'undefined' ? (import.meta.env as Record<string, string>)['VITE_SUPABASE_PUBLISHABLE_KEY'] : undefined) ||
    (typeof process !== 'undefined' ? process.env['SUPABASE_PUBLISHABLE_KEY'] : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing env vars: ${missing.join(', ')}. Running in demo mode.`);
    // Return a minimal stub that won't crash the app
    return createClient<Database>('https://placeholder.supabase.co', 'placeholder-key');
  }

  // Use brokered storage only in Lovable preview iframes; otherwise use localStorage directly.
  type AuthOptions = {
    storage?: Storage | undefined;
    persistSession?: boolean;
    autoRefreshToken?: boolean;
  };
  let storageAdapter: AuthOptions = {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  };

  if (isInLovablePreview()) {
    // Dynamically import the brokered storage only when needed
    try {
      const { brokeredPreviewStorage } = require('./previewAuthStorage');
      storageAdapter = {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
      };
    } catch {
      // Fall back to localStorage
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: storageAdapter,
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
